config/routes.rb
Rails.application.routes.draw do
  resources :todos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :create]
  resources :roles
  get '/enter' => 'board#enter', as: 'enter'
  get '/exit' => 'board#exit', as: 'exit'
  get '/board' => 'board#show', as: 'board'
  # resources :boards, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  validates :name, presence: true, length: {minimum: 4}
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :photo, FileUploader
  validates :name, presence: true, length: {minimum: 2}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    if (current_user_id = session[:current_user_id]).present?
      @current_user ||= User.find(current_user_id)
    end
    @current_user
  end
  helper_method :current_user
  
end

app/controllers/board_controller.rb
class BoardController < ApplicationController
  
  def enter
    session[:current_user_id] = params[:user_id]
    redirect_to board_path
  end

  def show
    @user = current_user 
    @users = User.all 
    @roles = Role.all 
    @todos = Todo.all 
  end

  def exit
    session[:current_user_id] = nil
    redirect_to users_path
  end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :fetch_role, only: [:show, :edit, :update, :destroy]

  def index
    @roles = Role.all
    @role = Role.new
  end

  def new
    @role = Role.new
  end

  def edit
  end

  def create
    @role = Role.new(role_params)

    if @role.save
      redirect_to roles_path
    else 
      render :new
    end
  end

  def show
    @role = Role.find(params[:id])
  end

  def update

    if @role.update_attributes(role_params)
      redirect_to role_path(@role)
    else 
      render :edit
    end
  end

  def destroy
    @role.destroy
    redirect_to roles_path
  end

  private

    def role_params
      params.require(:role).permit(:name)
    end

    def fetch_role
      @role = Role.find(params[:id])
    end

end   

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:title, :description, :status, :due_date)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if current_user.present?
      redirect_to board_path
    else
      @users = User.all
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to board_path(user_id: @user.id)
    else 
      render :index, notice: 'User cannot be empty'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/board/_navigation.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#"} MissionBoard
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to @user.name, ''
        %li
          = link_to 'Exit', exit_path

app/views/board/_sidebar.html.haml
%ul.nav.nav-sidebar
  %li.active
    %a{:href => "#"}
      Overview
      %span.sr-only (current)
  %li
    %a{:href => "#"} Reports
  %li
    %a{:href => "#"} Analytics
  %li
    %a{:href => "#"} Export
%ul.nav.nav-sidebar
  %li
    %a{:href => ""} Nav item
  %li
    %a{:href => ""} Nav item again
  %li
    %a{:href => ""} One more nav
  %li
    %a{:href => ""} Another nav item
  %li
    %a{:href => ""} More navigation
%ul.nav.nav-sidebar
  %li
    %a{:href => ""} Nav item again
  %li
    %a{:href => ""} One more nav
  %li
    %a{:href => ""} Another nav item

app/views/board/_todo_list.html.haml
%h2.sub-header To Do List
.table-responsive
  %table.table.table-striped
    %thead
      %tr
        %th #
        %th Header
        %th Header
        %th Header
        %th Header
    %tbody
      %tr
        %td 1,001
        %td Lorem
        %td ipsum
        %td dolor
        %td sit
      %tr
        %td 1,002
        %td amet
        %td consectetur
        %td adipiscing
        %td elit
      %tr
        %td 1,003
        %td Integer
        %td nec
        %td odio
        %td Praesent
      %tr
        %td 1,003
        %td libero
        %td Sed
        %td cursus
        %td ante

app/views/board/show.html.haml
= render 'navigation'
.container-fluid
  .row
    .col-sm-3.col-md-2.sidebar= render 'sidebar'
    .col-sm-9.col-sm-offset-3.col-md-10.col-md-offset-2.main= render 'todo_list'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MissionBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/roles/_form.html.haml
= form_for @role do |f|

  - if role.errors.any?
    #error_explanation
      %h2
        = pluralize(role.errors.count, "error")
        prohibited this role from being saved:
      %ul
        - role.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    = f.text_field :name

  .actions
    = f.submit
  

app/views/roles/edit.html.haml
%h1 Edit Role
= render 'form', role: @role
= link_to 'Show', @role
= link_to 'Back', roles_path

app/views/roles/index.html.haml
%p#notice= notice
%h1 Roles
%table
  %thead
    %tr
      %th Name
      %th{:colspan => "3"}
  %tbody
    - @roles.each do |role|
      %tr
        %td= role.name
        %td= link_to 'Show', role
        %td= link_to 'Edit', edit_role_path(role)
        %td= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Role', new_role_path

app/views/roles/new.html.haml
%h1 New Role
%p 
  = render 'form', role: @role
  = link_to 'Back', roles_path

app/views/roles/show.html.haml
%h1 Role Details

%p
  Name:
  = @role.name

= link_to 'Edit', edit_role_path(@role)
= link_to 'Back', roles_path

app/views/todos/_form.html.haml
= form_for(todo) do |f|
  - if todo.errors.any?
    #error_explanation
      %h2
        = pluralize(todo.errors.count, "error")
        prohibited this todo from being saved:
      %ul
        - todo.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :status
    = f.number_field :status
  .field
    = f.label :due_date
    = f.datetime_select :due_date
  .actions
    = f.submit

app/views/todos/_todo_list.html.haml
%h2.sub-header To Do List
.table-responsive
  %table.table.table-striped
    %thead
      %th Title
      %th Description
      %th Status
      %th Due Date
      %th 
    %tbody
      - @todos.each do |todo|
        %tr 
          %td= todo.title
          %td= todo.description
          %td= todo.status
          %td= todo.due_date
          %td Assignees
          %td= link_to 'Edit', edit_todo_path(todo)
          %td= link_to 'Destroy', 
        %tr
          %td{ colspan '7'}, =link_to 'New Todo', new_todo_path

app/views/todos/edit.html.haml
%h1 Editing Todo
= render 'form', todo: @todo
= link_to 'Show', @todo
|
\#{link_to 'Back', todos_path}

app/views/todos/index.html.haml
%p#notice= notice
%h1 Todos
%table
  %thead
    %tr
      %th Title
      %th Description
      %th Status
      %th Due date
      %th{:colspan => "3"}
  %tbody
    - @todos.each do |todo|
      %tr
        %td= todo.title
        %td= todo.description
        %td= todo.status
        %td= todo.due_date
        %td= link_to 'Show', todo
        %td= link_to 'Edit', edit_todo_path(todo)
        %td= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' }
%br
= link_to 'New Todo', new_todo_path

app/views/todos/new.html.haml
%h1 New Todo
= render 'form', todo: @todo
= link_to 'Back', todos_path

app/views/todos/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @todo.title
%p
  %strong Description:
  = @todo.description
%p
  %strong Status:
  = @todo.status
%p
  %strong Due date:
  = @todo.due_date
= link_to 'Edit', edit_todo_path(@todo)

= link_to 'Back', todos_path

app/views/users/_form.html.haml
= form_for @user do |f|
  .field
    = f.label :name
    = f.text_field :name

  .actions
    = f.submit
 

app/views/users/index.html.haml
.container.main

.container.marketing
  - if @users.present?
    .rows.users-list
      - @users.each do |user|
        .col-lg-4.labeled-image-box
          = link_to enter_path(user_id: user.id) do
            - if user.photo.present?
              = image_tag user.photo, style: 'width: 140px; height: 140px'
            - else 
              %img.img-circle{:alt => "Generic placeholder image", :height => "140", :src => "data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==", :width => "140"}/
            %h3= user.name

.new-user-form
  %h4 Neuer User?
  = form_for @user do |f|
    = f.label :name
    = f.text_field :name, style: 'width: 265px'
    %br
      %label Photo
      = f.file_field :photo, class: 'file-input'
    = f.submit